### ISSUE TITLE
Fix deploy script

### ISSUE THREAD

**Issue by lhguerra** [TallerWebSolutions/drupal-enterprise-boilerplate#19]
- [x] Add config to acquia dir `cp -r ./config/* $ACQUIA_DIR/config`

**Comment by sebas5384** [comment]
[ ] Create symbolic link of `web -> docroot` after copying build to acquia repo

**Comment by lhguerra** [comment]
@sebas5384 how about we starting using the docroot folder directly instead of web in our environments?

**Comment by lhguerra** [comment]
First comment ir already fixed and second comment is a duplication of #23
