### ISSUE TITLE
Add phpcs for Drupal coding standard

### ISSUE THREAD

**Issue by sebas5384** [TallerWebSolutions/drupal-enterprise-boilerplate#2]
1. Add phpcs.xml - ok
2. Add command at Makefile - ok
3. Add the verification at the ci-check.sh script - ok
4. Add the verification on the git hooks ? - #11

**Comment by lhguerra** [comment]
Just adding some more stuff to the list:

5. Add Drupal Coder module
6. Add `squizlabs/php_codesniffer` lib
7. Update README with instructions
8. Added symlink in bin folder

@sebas5384 about the git hooks, do you think it is a good idea to use the husky npm module to do that? On one hand, we already need npm dependencies in most of our projects. On the other, it might be the only thing in the boilerplate that relies on it (and that doesn't really need to), so I am unsure about this approach.

**Comment by lhguerra** [comment]
Work started in the branch `fs/issue-2-phpcs`
