### ISSUE TITLE
Drush can't be a dev dependency

### ISSUE THREAD

**Issue by lhguerra** [TallerWebSolutions/drupal-enterprise-boilerplate#43]
We use Drush in the Acquia hooks, and to get it in Acquia environments it need to be a regular dependency in composer.json, because the script `ci-install-prod` rules out dev dependencies.

**Comment by arthuralmeidap** [comment]
added alias for hooks

**Comment by arthuralmeidap** [comment]
moved drush from dev dependency and setup as regular dependency
